### ISSUE TITLE
An idea for twtm style

### ISSUE THREAD

**Issue by ZeynAlex** [UndertaleFan6/BEE2-TWTM-style#1]
Windows in thinking with time machine are actually just glass with skybox texture behind that shows 3d-skybox. You can add them to your package.
![Снимок экрана 2023-07-22 122426](https://github.com/UndertaleFan6/BEE2-TWTM-style/assets/100288527/b0c0ffe6-1921-408f-b635-9c5c41c47996)

**Comment by UndertaleFan6** [comment]
This will be in the next release!
